# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jQtGGd8OQVF9wX69xH7Dli2NjMCTIRc
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

# --- 1. CẤU HÌNH TRANG WEB ---
st.set_page_config(
    page_title="VietBank AI Dashboard",
    page_icon="🏦",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS để giao diện nhìn ngầu hơn (Dark Sidebar, Light Main)
st.markdown("""
<style>
    /* Chỉnh màu sidebar */
    [data-testid="stSidebar"] {
        background-color: #0f172a;
        color: #f8fafc;
    }
    [data-testid="stSidebar"] * {
        color: #f8fafc;
    }
    /* Chỉnh màu nút radio/select trong sidebar */
    .stRadio > div > label > div > div {
        color: #f8fafc !important;
    }
    /* Chỉnh title chính */
    .main-title {
        font-size: 2.5rem;
        font-weight: 700;
        color: #1e293b;
        margin-bottom: 0px;
    }
    .sub-title {
        color: #64748b;
        font-weight: 500;
        margin-bottom: 30px;
    }
    /* Highlight text trong tab */
    .metric-card {
        background-color: white;
        border: 1px solid #e2e8f0;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
</style>
""", unsafe_allow_html=True)


# --- 2. HÀM TẢI DỮ LIỆU ---
@st.cache_data
def load_data():
    try:
        df = pd.read_csv('processed_banking_data.csv')
        # Chuyển đổi một số cột quan trọng cho chắc chắn
        df['thoi_gian_nam_quy'] = df['thoi_gian_nam_quy'].astype(int)

        # Nếu data có nhiều NaN, fill tạm bằng 0 hoặc drop
        df = df.dropna(subset=['Cluster', 'ROA', 'NPL_Ratio', 'NIM'])
        df['Cluster'] = df['Cluster'].astype(int).astype(str) # Ép kiểu string để Plotly nhận diện là Category
        return df
    except FileNotFoundError:
        st.error("Không tìm thấy file 'processed_banking_data.csv'. Vui lòng chạy lại file final.py để xuất dữ liệu.")
        st.stop()

df = load_data()


# --- 3. SIDEBAR CONTROLS ---
with st.sidebar:
    st.markdown("## 📊 VietBank AI.")
    st.markdown("---")

    st.markdown("**WORKSPACE**")
    active_tab = st.radio(
        "Chọn chế độ phân tích:",
        ("Phân Tích Cụm (K-Means)", "Tương Quan Vĩ Mô (OLS)", "Deep Dive Dataset"),
        label_visibility="collapsed"
    )

    st.markdown("---")
    st.markdown("**⚙️ MODEL PARAMETERS**")

    # Lọc Năm
    min_year, max_year = int(df['thoi_gian_nam_quy'].min()), int(df['thoi_gian_nam_quy'].max())
    selected_years = st.slider("Giai đoạn phân tích (Năm):", min_value=min_year, max_value=max_year, value=(min_year, max_year))

    # Lọc Cụm
    all_clusters = sorted(df['Cluster'].unique().tolist())
    selected_clusters = st.multiselect("Lọc theo Cụm:", options=all_clusters, default=all_clusters)

    st.markdown("---")
    st.success("✅ Data pipeline processed successfully.")


# Lọc data dựa trên Sidebar
filtered_df = df[
    (df['thoi_gian_nam_quy'].between(selected_years[0], selected_years[1])) &
    (df['Cluster'].isin(selected_clusters))
]


# --- 4. MAIN CONTENT AREA ---

# Header
st.markdown('<p class="main-title">Phân Tích Chuyên Sâu Hệ Thống Ngân Hàng</p>', unsafe_allow_html=True)
st.markdown('<p class="sub-title">Based on OLS Regression & K-Means output (2020-2024)</p>', unsafe_allow_html=True)


# --- TAB 1: CLUSTERING ANALYSIS ---
if active_tab == "Phân Tích Cụm (K-Means)":

    col1, col2 = st.columns([2, 1])

    with col1:
        st.markdown("**Phân bố Ngân hàng theo Cụm (K-Means)**")
        st.caption("Trục X: Quy mô tài sản | Trục Y: Lợi nhuận (ROA) | Kích thước: Rủi ro nợ xấu (NPL)")

        # Lấy tên cột Asset thực tế (vì code của cậu đang map qua biến động)
        # Giả sử cột Asset là cột đầu tiên sau ticker và năm (hoặc ta tính lại giá trị trung bình)
        # Để an toàn, lấy điểm trung bình của từng ngân hàng trong giai đoạn được chọn
        df_scatter = filtered_df.groupby(['ticker', 'Cluster']).agg({
            'ROA': 'mean',
            'NPL_Ratio': 'mean',
            'NIM': 'mean'
            # Cần thêm Total_Assets nếu muốn x-axis chính xác, ở đây dùng NIM làm ví dụ thay thế nếu cột bị sai tên
        }).reset_index()

        # Plotly Scatter
        fig_scatter = px.scatter(
            df_scatter,
            x="NIM", # Thay bằng cột Asset nếu cậu có tên cột rõ ràng
            y="ROA",
            size="NPL_Ratio",
            color="Cluster",
            hover_name="ticker",
            color_discrete_sequence=['#10b981', '#f59e0b', '#ef4444'], # Xanh, Cam, Đỏ
            size_max=40,
            template="plotly_white"
        )
        fig_scatter.update_layout(margin=dict(l=0, r=0, t=30, b=0))
        st.plotly_chart(fig_scatter, use_container_width=True)

    with col2:
        st.markdown("**Hồ sơ Cụm (Cluster DNA)**")
        st.caption("Mức độ hoàn thiện các chỉ số trung bình")

        # Tính trung bình các KPI theo cụm
        radar_df = filtered_df.groupby('Cluster')[['ROA', 'NIM', 'CIR', 'NPL_Ratio']].mean().reset_index()

        # Chuẩn hóa (Normalize) nhẹ để vẽ Radar (chuyển về scale 0-100)
        # Đây là code giả lập logic vẽ radar
        categories = ['ROA', 'NIM', 'Hiệu quả Phí (CIR đảo)', 'Chất lượng TS (NPL đảo)']

        fig_radar = go.Figure()
        colors = {'0': '#10b981', '1': '#f59e0b', '2': '#ef4444'}

        for index, row in radar_df.iterrows():
            cluster_id = row['Cluster']
            if cluster_id in selected_clusters:
                # Đảo ngược CIR và NPL vì thấp mới là tốt
                values = [
                    row['ROA'] * 50, # Scale up x50 cho biểu đồ
                    row['NIM'] * 15, # Scale up
                    100 - (row['CIR'] * 100), # Đảo ngược
                    100 - (row['NPL_Ratio'] * 100) # Đảo ngược
                ]
                # Đóng vòng radar
                values.append(values[0])
                cat_closed = categories + [categories[0]]

                fig_radar.add_trace(go.Scatterpolar(
                    r=values,
                    theta=cat_closed,
                    fill='toself',
                    name=f'Cụm {cluster_id}',
                    line_color=colors.get(cluster_id, '#3b82f6')
                ))

        fig_radar.update_layout(
            polar=dict(radialaxis=dict(visible=False, range=[0, 100])),
            showlegend=True,
            margin=dict(l=40, r=40, t=30, b=0)
        )
        st.plotly_chart(fig_radar, use_container_width=True)

        st.info("💡 **Insight Model:** Cụm 0 thường cân bằng tốt nhất giữa TS, Lợi nhuận và Rủi ro. Cụm 2 gặp vấn đề về NPL.")

# --- TAB 2: MACRO CORRELATION ---
elif active_tab == "Tương Quan Vĩ Mô (OLS)":

    col1, col2 = st.columns([1, 2])

    with col1:
        st.markdown("<div class='metric-card' style='background:#1e1b4b; color:white;'>", unsafe_allow_html=True)
        st.markdown("### 📈 Kết quả Hồi quy (OLS Model)")
        st.markdown("---")
        st.markdown("🟢 **P-value < 0.05:** Tăng trưởng GDP có tương quan dương mạnh mẽ với ROA.")
        st.markdown("🔴 **Hệ số Beta (NPL):** Khi GDP suy giảm, tỷ lệ nợ xấu NPL có độ trễ (lag) và tăng mạnh vào năm tiếp theo.")
        st.markdown("🟡 **R-Squared:** Các biến vĩ mô giải thích phần lớn sự biến thiên lợi nhuận.")
        st.markdown("</div>", unsafe_allow_html=True)

    with col2:
        st.markdown("**Tác động GDP lên ROA & NPL hệ thống**")

        # Gom nhóm theo năm
        macro_df = df[df['thoi_gian_nam_quy'].between(selected_years[0], selected_years[1])]
        sys_trend = macro_df.groupby('thoi_gian_nam_quy').agg({
            'gdp_yoy_growth': 'mean',
            'ROA': 'mean',
            'NPL_Ratio': 'mean'
        }).reset_index()

        # Plotly Composed Chart (Bar + Line)
        fig_macro = go.Figure()

        # Cột GDP
        fig_macro.add_trace(go.Bar(
            x=sys_trend['thoi_gian_nam_quy'],
            y=sys_trend['gdp_yoy_growth'],
            name='GDP Growth (%)',
            marker_color='#cbd5e1',
            yaxis='y1'
        ))

        # Line ROA
        fig_macro.add_trace(go.Scatter(
            x=sys_trend['thoi_gian_nam_quy'],
            y=sys_trend['ROA'],
            name='ROA (%)',
            mode='lines+markers',
            marker=dict(color='#10b981', size=8),
            line=dict(width=3),
            yaxis='y2'
        ))

        # Line NPL
        fig_macro.add_trace(go.Scatter(
            x=sys_trend['thoi_gian_nam_quy'],
            y=sys_trend['NPL_Ratio'] * 100, # Nhân 100 nếu ratio là số thập phân
            name='NPL Ratio (%)',
            mode='lines+markers',
            marker=dict(color='#ef4444', size=8),
            line=dict(width=3),
            yaxis='y2'
        ))

        fig_macro.update_layout(
            yaxis=dict(title='GDP Growth', side='left', showgrid=False),
            yaxis2=dict(title='KPIs (%)', side='right', overlaying='y', showgrid=False),
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
            margin=dict(l=0, r=0, t=30, b=0),
            plot_bgcolor='white'
        )
        st.plotly_chart(fig_macro, use_container_width=True)

# --- TAB 3: DATASET & HEATMAP ---
elif active_tab == "Deep Dive Dataset":
    st.markdown("**Dataset Phân Tích (Cảnh báo tự động)**")

    # Lấy data trung bình cho từng ngân hàng trong khoảng thời gian đã chọn
    heatmap_data = filtered_df.groupby(['ticker', 'Cluster']).agg({
        'ROA': 'mean',
        'NIM': 'mean',
        'NPL_Ratio': 'mean',
        'CIR': 'mean'
    }).reset_index()

    # Nhân 100 cho dễ nhìn
    heatmap_data['NPL_Ratio'] = heatmap_data['NPL_Ratio'] * 100
    heatmap_data['CIR'] = heatmap_data['CIR'] * 100

    # Format lại dataframe để hiển thị đẹp bằng Pandas Styler
    def color_risk(val, metric):
        if pd.isna(val): return ''
        if metric == 'ROA':
            if val > 1.8: return 'background-color: #d1fae5; color: #047857; font-weight: bold' # Xanh lá
            if val < 1.0: return 'background-color: #ffe4e6; color: #be123c' # Đỏ nhạt
        elif metric == 'NPL':
            if val > 3.0: return 'background-color: #ffe4e6; color: #be123c; font-weight: bold'
            if val < 1.5: return 'background-color: #d1fae5; color: #047857'
        return ''

    styled_df = heatmap_data.style\
        .applymap(lambda x: color_risk(x, 'ROA'), subset=['ROA'])\
        .applymap(lambda x: color_risk(x, 'NPL'), subset=['NPL_Ratio'])\
        .format({
            "ROA": "{:.2f}%",
            "NIM": "{:.2f}%",
            "NPL_Ratio": "{:.2f}%",
            "CIR": "{:.2f}%"
        })

    st.dataframe(styled_df, use_container_width=True, height=500)